# SPDX-License-Identifier: GPL-3.0-only

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "org.joml:joml"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
      - dependency-name: "com.sk89q.worldguard:worldguard-bukkit"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
